# Step 1: Nginx 이미지 사용
FROM nginx:alpine

# 기존 Nginx 페이지 삭제
RUN rm -rf /usr/share/nginx/html/*

# Jenkins 빌드 결과물 디렉토리에서 Nginx로 복사 (여기서는 빌드된 dist 폴더)
# 빌드된 결과물은 Jenkins에서 마운트하여 사용
# COPY --from=build /app/dist /usr/share/nginx/html

COPY default.conf /etc/nginx/conf.d/default.conf

# 포트 노출
EXPOSE 5173
EXPOSE 443

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
